### ISSUE TITLE
Rake error

### ISSUE THREAD

**Issue by zlatanvasovic** [TryGhost/roon-i18n#50]
When run `rake incomplete` I got normal output, but this comes after it:

```
rake aborted!
undefined method `[]' for nil:NilClass

Tasks: TOP => incomplete
(See full trace by running task with --trace)
```

:(

**Comment by soffes** [comment]
Works for me. Can you provide the output of `rake incomplete --trace`?

**Comment by zlatanvasovic** [comment]
```
rake aborted!
undefined method `[]' for nil:NilClass
/home/zlatan/dev/git/fork/roon-sr/Rakefile:17:in `block (2 levels) in <top (required)>'
/home/zlatan/dev/git/fork/roon-sr/Rakefile:9:in `foreach'
/home/zlatan/dev/git/fork/roon-sr/Rakefile:9:in `block in <top (required)>'
/usr/lib/ruby/vendor_ruby/rake/task.rb:205:in `call'
/usr/lib/ruby/vendor_ruby/rake/task.rb:205:in `block in execute'
/usr/lib/ruby/vendor_ruby/rake/task.rb:200:in `each'
/usr/lib/ruby/vendor_ruby/rake/task.rb:200:in `execute'
/usr/lib/ruby/vendor_ruby/rake/task.rb:158:in `block in invoke_with_call_chain'
/usr/lib/ruby/1.9.1/monitor.rb:211:in `mon_synchronize'
/usr/lib/ruby/vendor_ruby/rake/task.rb:151:in `invoke_with_call_chain'
/usr/lib/ruby/vendor_ruby/rake/task.rb:144:in `invoke'
/usr/lib/ruby/vendor_ruby/rake/application.rb:116:in `invoke_task'
/usr/lib/ruby/vendor_ruby/rake/application.rb:94:in `block (2 levels) in top_level'
/usr/lib/ruby/vendor_ruby/rake/application.rb:94:in `each'
/usr/lib/ruby/vendor_ruby/rake/application.rb:94:in `block in top_level'
/usr/lib/ruby/vendor_ruby/rake/application.rb:133:in `standard_exception_handling'
/usr/lib/ruby/vendor_ruby/rake/application.rb:88:in `top_level'
/usr/lib/ruby/vendor_ruby/rake/application.rb:66:in `block in run'
/usr/lib/ruby/vendor_ruby/rake/application.rb:133:in `standard_exception_handling'
/usr/lib/ruby/vendor_ruby/rake/application.rb:63:in `run'
/usr/bin/rake:27:in `<main>'
Tasks: TOP => incomplete
```

(on Ruby 1.9.3)

**Comment by zlatanvasovic** [comment]
I'm getting the same errors with Ruby 2.1.0 and new Rake.
